<?php
$category = strip_tags($_GET['type'] );
$pageVars = array(
	'css' => array('den-work'),
	'title' => '',
	'category'=>$category,
	'js'	=>array('macy','projects')
);
include('../../header.php');
?>
<main id="content-sections-wrap">
    <section id="project-intro"
             class="container">
        <div class="flex-row outdent flex-vcenter">
            <div class="preview-image col5l col5m col4s col12x vertical">
                <img src="v01design.png"
                 alt="design for improved invoice layout">
            </div>
            <div class="col7l col7m col8s col12x">
                <h1 class="project-title h1">Invoice Template Design</h1>
                <p class="h4 project-date uiux">UI/UX Design </p>
                <p class="h4 project-date dev">Dev</p>
                <p class="h4 project-date gd">Design</p>
                <h2 class="h3">Summary</h2>
                <p>Improving the layout of system generated invoices to improve user satisfaction and reduce paper waste.</p>
            </div>
        </div>
    </section>
    <section id="project-process"
             class="accent-bar">
        <div class="container clearfix">
            <div class="row outdent">
                <div class="col12x col4s col4m col4l">
                    <h2 class="h3 no-vpad"><span class="uiux">Design</span><span class="gd">Design</span><span
                              class="dev">Development</span> Process</h2>
                    <p class=" uiux">
                        I was assigned to to the engineering and design work for this project. Our customers wanted several small improvements to the invoices generated by our software, as well as the ability to use them with windowed envelopes.
                    </p>
                    <p>I enjoyed doing the design work, and trying to get the alignment of pts  and pixels and final printed output to match.</p>
                    <p>The process we were using to generate the pdfs was very difficult to understand, and in the end, our Senior Front-End Engineer took over the implementation.</p>
                </div>
                <div class=" col12x col8s col8m col8l">
                    <div id="invoices-gallery"
                         class="project-gallery "
                         data-sizes="3333">
                        <figure class="project-img">
                            <a href="v00invoice01.jpg"><img src="v00invoice01.jpg"
                                     alt="original invoice design"></a>
                            <figcaption>original invoice design</figcaption>
                        </figure>
                        <figure class="project-img">
                            <a href="v01design.png"><img src="v01design.png"
                                     alt="improved invoice design"></a>
                            <figcaption>improved invoice design</figcaption>
                        </figure>
                        <figure class="project-img">
                            <a href="v01grid.png"><img src="v01grid.png"
                                     alt="testing layout for fitting in windowed envelopes and prepping to convert from points to pixels"></a>
                            <figcaption>testing layout for windowed envelopes and converting from points to
                                pixelsoriginal invoice design</figcaption>
                        </figure>
                    </div>
                </div>
            </div>
    </section>
    <section id="project-results"
             class="container">
        <div class="flex-row outdent">
            <div class="col12x col6s col5m col4l">
                <h2 class="h3">The Final <span class="uiux">Design</span><span class="gd">Design</span><span
                          class="dev">Product</span> </h2>
                <p class="uiux"></p>
                <p class="dev"></p>
                <p class="gd"></p>
                <p>The final implemented design.</p>
            </div>
            <div class="col12x col6s col7m col8l">
                <div class="project-gallery">
                    <figure class="project-img">
                        <img src="v02final.png"
                             alt="final design">
                    </figure>
                </div>
            </div>
        </div>
    </section>
</main>
<?php include('../../footer.php');