baseURL = "https://denisenadal.com"
languageCode = "en-us"
title = "Denise Nadal"
theme = 'dn-theme'
googleAnalytics= " UA-70117950-2"

[taxonomies]
  post = "posts"
  tag = "tags"
  work = "work"
[params]
    env    = "PUBLIC"