[build]
publish = "public"
command = "npm run build"

[context.production.environment]
HUGO_VERSION = "0.101.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

NPM_VERSION = "8.6.0"
NODE_VERSION ="17.7.2"

[context.branch-deploy]
HUGO_ENV = "testing"
